const globalColorList = [
  // Gelb/Rot (Yellow-Red) - YR
  "orange",
  "darkorange",
  "coral",
  "tomato",
  "orangered",
  "goldenrod",
  "darkgoldenrod",
  "peru",
  "chocolate",
  "sandybrown",
  "saddlebrown",
  "burlywood",
  "tan",

  // Rot (Red) - R
  "red",
  "firebrick",
  "darkred",
  "indianred",
  "lightcoral",
  "salmon",
  "darksalmon",
  "lightsalmon",
  "crimson",

  // Rot/Blau (Red-Blue) - RB
  "maroon",
  "brown",
  "rosybrown",
  "mistyrose",
  "pink",
  "lightpink",
  "hotpink",
  "deeppink",
  "palevioletred",
  "mediumvioletred",
  "lavenderblush",
  "orchid",
  "plum",
  "thistle",
  "violet",
  "fuchsia",
  "magenta",

  // Blau (Blue) - B
  "blue",
  "mediumblue",
  "darkblue",
  "navy",
  "midnightblue",
  "royalblue",
  "dodgerblue",
  "cornflowerblue",
  "deepskyblue",
  "skyblue",
  "lightskyblue",
  "lightsteelblue",
  "steelblue",
  "powderblue",
  "cadetblue",
  "slateblue",
  "darkslateblue",
  "mediumslateblue",

  // Blau/Grün (Blue-Green) - BG
  "cyan",
  "aqua",
  "lightcyan",
  "paleturquoise",
  "aquamarine",
  "turquoise",
  "mediumturquoise",
  "darkturquoise",
  "lightseagreen",
  "cadetblue",
  "darkcyan",
  "teal",

  // Grün (Green) - G
  "green",
  "darkgreen",
  "darkolivegreen",
  "olivedrab",
  "yellowgreen",
  "limegreen",
  "lime",
  "lawngreen",
  "chartreuse",
  "greenyellow",
  "springgreen",
  "mediumspringgreen",
  "lightgreen",
  "palegreen",
  "mediumseagreen",
  "seagreen",
  "forestgreen",

  // Grün/Gelb (Green-Yellow) - GY
  "olive",
  "darkseagreen",
  "honeydew",
  "mintcream",

  // Neutral (Grays/Neutrals)
  "black",
  "dimgray",
  "gray",
  "darkgray",
  "silver",
  "lightgray",
  "gainsboro",
  "whitesmoke",
  "white",
  "ivory",
  "beige",
  "linen",
  "antiquewhite",
  "oldlace",
  "floralwhite",
  "seashell",
  "snow",
  "ghostwhite",
  "aliceblue",
  "azure",
  "lavender",
  "lightcyan",
];
